spring.application.name=learn-mcp
server.port=8081

#OpenAI Configuration
spring.ai.openai.api-key=${OPENAI_API_KEY}

#Logging Configuration
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#MCP Server Configuration
spring.ai.mcp.client.stdio.servers-configuration=classpath:servers.json
